import ContactDetails from "@/components/ContactDetails";
import Link from "next/link";
import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="bg-background text-foreground p-8">
      <div className="max-w-4xl mx-auto bg-card p-6 shadow-md rounded-md">
        <h1 className="text-2xl font-bold mb-4 text-center">
          Terms and Conditions
        </h1>
        {/* A - Information Technology Act */}
        <p className="mb-6">
          <strong>A.</strong> This document is an electronic record in terms of
          the Information Technology Act, 2000 and rules thereunder as
          applicable and the amended provisions pertaining to electronic records
          in various statutes as amended by the Information Technology Act,
          2000. This electronic record is generated by a computer system and
          does not require any physical or digital signatures.
        </p>
        {/* B - Rule 3 (1) Compliance */}
        <p className="mb-6">
          <strong>B.</strong> This document is published in accordance with the
          provisions of Rule 3 (1) of the Information Technology (Intermediaries
          guidelines) Rules, 2011 that require publishing the rules and
          regulations, privacy policy, and Terms of Use for access or usage of
          domain name [Enter domain name] (“Website”), including the related
          mobile site and mobile application (hereinafter referred to as
          “Platform”).
        </p>
        {/* C - Platform Ownership */}
        <p className="mb-6">
          <strong>C.</strong> The Platform is owned by{" "}
          <b>Maa Kali Griha Udyog</b>, a company incorporated under the
          Companies Act, 1956 with its registered office at Maa Kali Griha
          Udyog, PT Road, near Kedia Dharamshala, Koritola, Pachamba, Giridih,
          Jharkhand 815316 (hereinafter referred to as
          {`"Platform Owner", “we”, “us”, “our”`}).
        </p>
        {/* D - User Obligations */}
        <p className="mb-6">
          <strong>D.</strong> Your use of the Platform and services and tools
          are governed by the following terms and conditions{" "}
          {`("Terms of Use")`} as applicable to the Platform, including the
          applicable policies which are incorporated herein by reference. If You
          transact on the Platform, You shall be subject to the policies that
          are applicable to the Platform for such transactions. By mere use of
          the Platform, You shall be contracting with the Platform Owner and
          these terms and conditions, including the policies, constitute Your
          binding obligations with the Platform Owner.
        </p>
        {/* E - User Definition */}
        <p className="mb-6">
          <strong>E.</strong> For the purpose of these Terms of Use,{" "}
          {`"you",
          “your” or "user"`}{" "}
          shall mean any natural or legal person who has agreed to become a
          user/buyer on the Platform.
        </p>
        {/* F - User Agreement */}
        <p className="mb-6">
          <strong>F.</strong> ACCESSING, BROWSING OR OTHERWISE USING THE
          PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS
          UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY
          BEFORE PROCEEDING.
        </p>
        {/* G - Terms of Use */}
        <h2 className="text-xl font-semibold mb-4">G. Terms of Use:</h2>
        <ul className="list-disc pl-6 mb-6">
          <li className="mb-2">
            <strong>I.</strong> You agree to provide true, accurate, and
            complete information during and after registration.
          </li>
          <li className="mb-2">
            <strong>II.</strong> Neither we nor any third parties provide any
            warranty as to the accuracy, performance, or suitability of the
            information and materials on this platform.
          </li>
          <li className="mb-2">
            <strong>III.</strong> Your use of the Platform and Services is at
            your own risk, and we shall not be liable for any such risks.
          </li>
          <li className="mb-2">
            <strong>IV.</strong> The contents of the Platform are proprietary,
            and you will not claim any intellectual property rights over them.
          </li>
          <li className="mb-2">
            <strong>V.</strong> Unauthorized use of the Platform or Services may
            lead to legal action.
          </li>
          <li className="mb-2">
            <strong>VI.</strong> You agree to pay the charges associated with
            using the Services.
          </li>
          <li className="mb-2">
            <strong>VII.</strong> You agree not to use the Platform for any
            unlawful purposes.
          </li>
          <li className="mb-2">
            <strong>VIII.</strong> Third-party website links are provided for
            convenience, and their usage is governed by the third party’s terms.
          </li>
          <li className="mb-2">
            <strong>IX.</strong> Upon initiating a transaction, you are entering
            into a legally binding contract with the Platform Owner.
          </li>
          <li className="mb-2">
            <strong>X.</strong> You agree to indemnify and hold the Platform
            Owner harmless from any third-party claims.
          </li>
          <li className="mb-2">
            <strong>XI.</strong> In no event shall the Platform Owner be liable
            for indirect or consequential damages.
          </li>
          <li className="mb-2">
            <strong>XII.</strong> Force majeure events prevent liability in the
            case of non-performance.
          </li>
          <li className="mb-2">
            <strong>XIII.</strong> These Terms shall be governed by the laws of
            India.
          </li>
          <li className="mb-2">
            <strong>XIV.</strong> All disputes shall be subject to the
            jurisdiction of the courts in Giridih Jharkhand.
          </li>
          <li className="mb-2">
            <strong>XV.</strong> Concerns or communications related to these
            Terms should be sent using the contact information provided on this
            website.
          </li>
        </ul>
        {/* Minimum Order Value */}
        <h2 className="text-xl font-semibold mb-4">Minimum Order Value</h2>
        <p className="mb-6">
          Orders must meet a minimum value of ₹499/- to be processed.
        </p>
        {/* Order Acceptance */}
        <h2 className="text-xl font-semibold mb-4">
          Order Acceptance and Rejection
        </h2>
        <p className="mb-6">
          When you place an order, it may not be accepted instantly. In some
          cases, we may reject an order due to stock issues, payment problems,
          or other reasons. If your order is rejected, you will be notified, and
          any payment made will be refunded within 7 business days.
        </p>
        {/* Order Processing and Delivery */}
        <h2 className="text-xl font-semibold mb-4">
          Order Processing and Delivery
        </h2>
        <p className="mb-6">
          Orders are processed within 2-3 business days. Delivery times vary
          depending on the location.
        </p>
        {/* Returns */}
        <h2 className="text-xl font-semibold mb-4">Returns</h2>
        <p className="mb-6">
          We do not accept returns. Please ensure that you are certain of your
          purchase before completing the transaction.
        </p>
        {/* Wholesale Orders */}
        <h2 className="text-xl font-semibold mb-4">Wholesale Orders</h2>
        <p className="mb-6">
          For bulk or B2B orders, please contact us directly at{" "}
          <Link href="/contact/" className="text-blue-600 hover:underline">
            here
          </Link>{" "}
          for special terms and pricing.
        </p>
        {/* Pricing and Availability */}
        <h2 className="text-xl font-semibold mb-4">Pricing and Availability</h2>
        <p className="mb-6">
          Prices may change without prior notice. Product availability may vary
          and is subject to change without notice.
        </p>
        {/* Contact Information */}
        <h2 className="text-xl font-semibold mb-4">Contact Information</h2>
        <div className="mb-6">
          For queries or support, reach out to us at{" "}
          <div className="flex flex-col-reverse gap-4 mt-2">
            <ContactDetails />
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
